### ISSUE TITLE
pip install -r requirements.txt 出错了

### ISSUE THREAD

**Issue by yollpoll** [TransparentLC/xdcmd#1]
ERROR: Could not find a version that satisfies the requirement prompt-toolkit==3.* (from -r requirements.txt (line 3)) (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.8, 0.9, 0.10, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.20, 0.21, 0.22, 0.23, 0.25, 0.26, 0.28, 0.30, 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.40, 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.50, 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.60, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.0.10, 1.0.13, 1.0.14, 1.0.15, 1.0.16, 1.0.17, 1.0.18, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.0.10)
ERROR: No matching distribution found for prompt-toolkit==3.* (from -r requirements.txt (line 3))

**Comment by TransparentLC** [comment]
也许是你使用的 pypi 源的问题？在 pypi 上 prompt-toolkit 是有 3.* 的版本的。

https://pypi.org/project/prompt-toolkit/#history
