### ISSUE TITLE
启动出错，报  module 'functools' has no attribute 'cache'

### ISSUE THREAD

**Issue by traburiss** [TransparentLC/xdcmd#2]
环境以及终端信息
windows 11 wsl2 ubuntun 20.04
windows terminal
python 3.8
pip 20.0.2

pip已经执行，执行python3 main.py后报以下错误：
`
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    import xdnmb.globals
  File "/mnt/d/develop/project/python/xdcmd/xdnmb/globals.py", line 5, in <module>
    import xdnmb.action
  File "/mnt/d/develop/project/python/xdcmd/xdnmb/action.py", line 1, in <module>
    import xdnmb.api
  File "/mnt/d/develop/project/python/xdcmd/xdnmb/api.py", line 8, in <module>
    import xdnmb.model
  File "/mnt/d/develop/project/python/xdcmd/xdnmb/model.py", line 28, in <module>
    class Forum:
  File "/mnt/d/develop/project/python/xdcmd/xdnmb/model.py", line 35, in Forum
    @functools.cache
AttributeError: module 'functools' has no attribute 'cache'
`

截图：
![image](https://user-images.githubusercontent.com/14953133/182610682-1d554de2-3ec0-4d84-8a93-0e07a229a065.png)

肥哥有空的时候麻烦看一眼~~我才是不是奇奇怪怪的版本问题？

**Comment by TransparentLC** [comment]
看样子你这里用的是 Python 3.8，但是[`functools.cache`](https://docs.python.org/zh-cn/3/library/functools.html#functools.cache) 是 Python 3.9 才加入的。

不过实际上这也就是个在不考虑大小限制的情况下使用 `functools.lru_cache`（这个在 Python 3.2 就加入了）的[别名](https://github.com/python/cpython/blob/f9433fff476aa13af9cb314fcc6962055faa4085/Lib/functools.py#L647)，如果要在 Python 3.8 或以下使用的话需要把所有的 `functools.cache` 替换成 `functools.lru_cache(maxsize=None)`。

以及改一下和那个类型注释有关的东西……

> \>\>No.50916848
> 其实是因为我加了类型注释( ﾟ∀。)
> 
> 用了很多 `a|b|...` 这样的类型注释，但是这种写法是 3.10 才加入的，所以旧版就运行不了了。在此之前的等效写法是 `typing.Union[a, b, ...]`（如果是 `a|None` 的话也可以用 `typing.Optional[a]`）。

**Comment by traburiss** [comment]
看起来升级python应该更快速一点…… 

> 看样子你这里用的是 Python 3.8，但是[`functools.cache`](https://docs.python.org/zh-cn/3/library/functools.html#functools.cache) 是 Python 3.9 才加入的。
> 
> 不过实际上这也就是个在不考虑大小限制的情况下使用 `functools.lru_cache`（这个在 Python 3.2 就加入了）的[别名](https://github.com/python/cpython/blob/f9433fff476aa13af9cb314fcc6962055faa4085/Lib/functools.py#L647)，如果要在 Python 3.8 或以下使用的话需要把所有的 `functools.cache` 替换成 `functools.lru_cache(maxsize=None)`。
> 
> 以及改一下和那个类型注释有关的东西……
> 
> > >>No.50916848
> > 其实是因为我加了类型注释( ﾟ∀。)
> > 用了很多 `a|b|...` 这样的类型注释，但是这种写法是 3.10 才加入的，所以旧版就运行不了了。在此之前的等效写法是 `typing.Union[a, b, ...]`（如果是 `a|None` 的话也可以用 `typing.Optional[a]`）。
