### ISSUE TITLE
MacOS中快捷键映射问题

### ISSUE THREAD

**Issue by liulifox233** [TransparentLC/xdcmd#8]
在MacOS终端中，option键默认不会映射到alt键上，导致无法使用，需要特殊设置。
请问不使用常用的ctrl键是有什么特殊的考量吗？

**Comment by TransparentLC** [comment]
我其实也有点忘了为什么设成 <kbd>Alt</kbd>了，可能是因为担心误按到 <kbd>Ctrl+C</kbd>，或者是左手操作的话大拇指按 <kbd>Alt</kbd> 会比小拇指按 <kbd>Ctrl</kbd> 更舒服一些。

对于 PR 有个问题，选择版面/串的两个键，左/右边的键对应向下/上，是不是反了？

**Comment by liulifox233** [comment]
呃事实上jk的操作是对应vim的操作习惯( ﾟ∀。)vim中上是k下是j来着

**Comment by TransparentLC** [comment]
( ﾟ∀。) 原来如此
